# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARC
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'FirebaseDatabase'
  pod 'FirebaseFirestore'
  pod 'GoogleSignIn'
  target 'ARCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARCUITests' do
    # Pods for testing
  end


end
